import APPEAL from "./APPEAL";
import ATTACKAIRB from './ATTACKAIRB';
import ATTACKAIRD from './ATTACKAIRD';
import ATTACKAIRF from './ATTACKAIRF';
import ATTACKAIRN from './ATTACKAIRN';
import ATTACKAIRU from './ATTACKAIRU';
import ATTACKDASH from './ATTACKDASH';
import CATCHATTACK from './CATCHATTACK';
import CLIFFATTACKQUICK from './CLIFFATTACKQUICK';
import CLIFFATTACKSLOW from './CLIFFATTACKSLOW';
import CLIFFESCAPEQUICK from './CLIFFESCAPEQUICK';
import CLIFFESCAPESLOW from './CLIFFESCAPESLOW';
import CLIFFGETUPQUICK from './CLIFFGETUPQUICK';
import CLIFFGETUPSLOW from './CLIFFGETUPSLOW';
import CLIFFJUMPQUICK from './CLIFFJUMPQUICK';
import CLIFFJUMPSLOW from './CLIFFJUMPSLOW';
import DOWNATTACK from './DOWNATTACK';
import DOWNSMASH from './DOWNSMASH';
import DOWNSPECIALAIR from './DOWNSPECIALAIR';
import DOWNSPECIALAIR2 from './DOWNSPECIALAIR2';
import DOWNSPECIALGROUND from './DOWNSPECIALGROUND';
import DOWNSPECIALGROUND2 from './DOWNSPECIALGROUND2';
import DOWNTILT from './DOWNTILT';
import FORWARDSMASH from './FORWARDSMASH';
import FORWARDTILT from './FORWARDTILT';
import GRAB from './GRAB';
import JAB1 from './JAB1';
import JAB2 from './JAB2';
import NEUTRALSPECIALAIR from './NEUTRALSPECIALAIR';
import NEUTRALSPECIALGROUND from './NEUTRALSPECIALGROUND';
import SIDESPECIALAIR from './SIDESPECIALAIR';
import SIDESPECIALAIR2FORWARD from './SIDESPECIALAIR2FORWARD';
import SIDESPECIALAIR2UP from './SIDESPECIALAIR2UP';
import SIDESPECIALAIR3DOWN from './SIDESPECIALAIR3DOWN';
import SIDESPECIALAIR3FORWARD from './SIDESPECIALAIR3FORWARD';
import SIDESPECIALAIR3UP from './SIDESPECIALAIR3UP';
import SIDESPECIALAIR4DOWN from './SIDESPECIALAIR4DOWN';
import SIDESPECIALAIR4FORWARD from './SIDESPECIALAIR4FORWARD';
import SIDESPECIALAIR4UP from './SIDESPECIALAIR4UP';
import SIDESPECIALGROUND from './SIDESPECIALGROUND';
import SIDESPECIALGROUND2FORWARD from './SIDESPECIALGROUND2FORWARD';
import SIDESPECIALGROUND2UP from './SIDESPECIALGROUND2UP';
import SIDESPECIALGROUND3DOWN from './SIDESPECIALGROUND3DOWN';
import SIDESPECIALGROUND3FORWARD from './SIDESPECIALGROUND3FORWARD';
import SIDESPECIALGROUND3UP from './SIDESPECIALGROUND3UP';
import SIDESPECIALGROUND4DOWN from './SIDESPECIALGROUND4DOWN';
import SIDESPECIALGROUND4FORWARD from './SIDESPECIALGROUND4FORWARD';
import SIDESPECIALGROUND4UP from './SIDESPECIALGROUND4UP';
import THROWBACK from './THROWBACK';
import THROWDOWN from './THROWDOWN';
import THROWFORWARD from './THROWFORWARD';
import THROWNFOXBACK from './THROWNFOXBACK';
import THROWNFOXDOWN from './THROWNFOXDOWN';
import THROWNFOXFORWARD from './THROWNFOXFORWARD';
import THROWNFOXUP from './THROWNFOXUP';
import THROWNMARTHBACK from './THROWNMARTHBACK';
import THROWNMARTHDOWN from './THROWNMARTHDOWN';
import THROWNMARTHFORWARD from './THROWNMARTHFORWARD';
import THROWNMARTHUP from './THROWNMARTHUP';
import THROWNPUFFBACK from './THROWNPUFFBACK';
import THROWNPUFFDOWN from './THROWNPUFFDOWN';
import THROWNPUFFFORWARD from './THROWNPUFFFORWARD';
import THROWNPUFFUP from './THROWNPUFFUP';
import THROWUP from './THROWUP';
import UPSMASH from './UPSMASH';
import UPSPECIAL from './UPSPECIAL';
import UPTILT from './UPTILT';
import THROWNFALCOUP from "./THROWNFALCOUP";
import THROWNFALCODOWN from "./THROWNFALCODOWN";
import THROWNFALCOBACK from "./THROWNFALCOBACK";
import THROWNFALCOFORWARD from "./THROWNFALCOFORWARD";
import THROWNFALCONUP from "./THROWNFALCONUP";
import THROWNFALCONDOWN from "./THROWNFALCONDOWN";
import THROWNFALCONBACK from "./THROWNFALCONBACK";
import THROWNFALCONFORWARD from "./THROWNFALCONFORWARD";


export default {
  ATTACKAIRB,
  ATTACKAIRD,
  ATTACKAIRF,
  ATTACKAIRN,
  ATTACKAIRU,
  ATTACKDASH,
  CATCHATTACK,
  CLIFFATTACKQUICK,
  CLIFFATTACKSLOW,
  CLIFFESCAPEQUICK,
  CLIFFESCAPESLOW,
  CLIFFGETUPQUICK,
  CLIFFGETUPSLOW,
  CLIFFJUMPQUICK,
  CLIFFJUMPSLOW,
  DOWNATTACK,
  DOWNSMASH,
  DOWNSPECIALAIR,
  DOWNSPECIALAIR2,
  DOWNSPECIALGROUND,
  DOWNSPECIALGROUND2,
  DOWNTILT,
  FORWARDSMASH,
  FORWARDTILT,
  GRAB,
  JAB1,
  JAB2,
  NEUTRALSPECIALAIR,
  NEUTRALSPECIALGROUND,
  SIDESPECIALAIR,
  SIDESPECIALAIR2FORWARD,
  SIDESPECIALAIR2UP,
  SIDESPECIALAIR3DOWN,
  SIDESPECIALAIR3FORWARD,
  SIDESPECIALAIR3UP,
  SIDESPECIALAIR4DOWN,
  SIDESPECIALAIR4FORWARD,
  SIDESPECIALAIR4UP,
  SIDESPECIALGROUND,
  SIDESPECIALGROUND2FORWARD,
  SIDESPECIALGROUND2UP,
  SIDESPECIALGROUND3DOWN,
  SIDESPECIALGROUND3FORWARD,
  SIDESPECIALGROUND3UP,
  SIDESPECIALGROUND4DOWN,
  SIDESPECIALGROUND4FORWARD,
  SIDESPECIALGROUND4UP,
  THROWBACK,
  THROWDOWN,
  THROWFORWARD,
  THROWNFOXBACK,
  THROWNFOXDOWN,
  THROWNFOXFORWARD,
  THROWNFOXUP,
  THROWNMARTHBACK,
  THROWNMARTHDOWN,
  THROWNMARTHFORWARD,
  THROWNMARTHUP,
  THROWNPUFFBACK,
  THROWNPUFFDOWN,
  THROWNPUFFFORWARD,
  THROWNPUFFUP,
  THROWUP,
  UPSMASH,
  UPSPECIAL,
  UPTILT,
  THROWNFALCOUP,
  THROWNFALCODOWN,
  THROWNFALCOBACK,
  THROWNFALCOFORWARD,
  THROWNFALCONUP,
  THROWNFALCONDOWN,
  THROWNFALCONBACK,
  THROWNFALCONFORWARD,
  APPEAL
};