const AERIALTURN1 = require("./AERIALTURN1");
const CLIFFGETUPSLOW = require("./CLIFFGETUPSLOW");
const DOWNSTANDB = require("./DOWNSTANDB");
const JUMPAERIAL2 = require("./JUMPAERIAL2");
const RUNBRAKE = require("./RUNBRAKE");
const THROWNFOXUP = require("./THROWNFOXUP");
const AERIALTURN2 = require("./AERIALTURN2");
const CLIFFJUMPQUICK = require("./CLIFFJUMPQUICK");
const DOWNSTANDF = require("./DOWNSTANDF");
const JUMPAERIAL3 = require("./JUMPAERIAL3");
const RUNTURN = require("./RUNTURN");
const THROWNMARTHBACK = require("./THROWNMARTHBACK");
const AERIALTURN3 = require("./AERIALTURN3");
const CLIFFJUMPSLOW = require("./CLIFFJUMPSLOW");
const DOWNSTANDN = require("./DOWNSTANDN");
const JUMPAERIAL4 = require("./JUMPAERIAL4");
const SHIELDBREAKDOWNBOUND = require("./SHIELDBREAKDOWNBOUND");
const THROWNMARTHDOWN = require("./THROWNMARTHDOWN");
const AERIALTURN4 = require("./AERIALTURN4");
const CLIFFWAIT = require("./CLIFFWAIT");
const DOWNTILT = require("./DOWNTILT");
const JUMPAERIAL5 = require("./JUMPAERIAL5");
const SHIELDBREAKFALL = require("./SHIELDBREAKFALL");
const THROWNMARTHFORWARD = require("./THROWNMARTHFORWARD");
const AERIALTURN5 = require("./AERIALTURN5");
const DAMAGEFALL = require("./DAMAGEFALL");
const DOWNWAIT = require("./DOWNWAIT");
const JUMPB = require("./JUMPB");
const SHIELDBREAKFLY = require("./SHIELDBREAKFLY");
const THROWNMARTHUP = require("./THROWNMARTHUP");
const ATTACKAIRB = require("./ATTACKAIRB");
const DAMAGEFLYHI = require("./DAMAGEFLYHI");
const ENTRANCE = require("./ENTRANCE");
const JUMPF = require("./JUMPF");
const SHIELDBREAKSTAND = require("./SHIELDBREAKSTAND");
const THROWNPUFFBACK = require("./THROWNPUFFBACK");
const ATTACKAIRD = require("./ATTACKAIRD");
const DAMAGEFLYLW = require("./DAMAGEFLYLW");
const ESCAPEAIR = require("./ESCAPEAIR");
const KNEEBEND = require("./KNEEBEND");
const SIDESPECIALAIR = require("./SIDESPECIALAIR");
const THROWNPUFFDOWN = require("./THROWNPUFFDOWN");
const ATTACKAIRF = require("./ATTACKAIRF");
const DAMAGEFLYN = require("./DAMAGEFLYN");
const ESCAPEB = require("./ESCAPEB");
const LANDING = require("./LANDING");
const SIDESPECIALGROUND = require("./SIDESPECIALGROUND");
const THROWNPUFFFORWARD = require("./THROWNPUFFFORWARD");
const ATTACKAIRN = require("./ATTACKAIRN");
const DAMAGEFLYTOP = require("./DAMAGEFLYTOP");
const ESCAPEF = require("./ESCAPEF");
const LANDINGATTACKAIRB = require("./LANDINGATTACKAIRB");
const SLEEP = require("./SLEEP");
const THROWNPUFFUP = require("./THROWNPUFFUP");
const ATTACKAIRU = require("./ATTACKAIRU");
const DAMAGEHI1 = require("./DAMAGEHI1");
const ESCAPEN = require("./ESCAPEN");
const LANDINGATTACKAIRD = require("./LANDINGATTACKAIRD");
const SMASHTURN = require("./SMASHTURN");
const THROWUP = require("./THROWUP");
const ATTACKDASH = require("./ATTACKDASH");
const DAMAGEHI2 = require("./DAMAGEHI2");
const FALL = require("./FALL");
const LANDINGATTACKAIRF = require("./LANDINGATTACKAIRF");
const SQUAT = require("./SQUAT");
const TILTTURN = require("./TILTTURN");
const CAPTURECUT = require("./CAPTURECUT");
const DAMAGEHI3 = require("./DAMAGEHI3");
const FALLSPECIAL = require("./FALLSPECIAL");
const LANDINGATTACKAIRN = require("./LANDINGATTACKAIRN");
const SQUATRV = require("./SQUATRV");
const UPSMASH = require("./UPSMASH");
const CAPTUREDAMAGE = require("./CAPTUREDAMAGE");
const DAMAGEN2 = require("./DAMAGEN2");
const FORWARDSMASH = require("./FORWARDSMASH");
const LANDINGATTACKAIRU = require("./LANDINGATTACKAIRU");
const SQUATWAIT = require("./SQUATWAIT");
const UPSPECIAL = require("./UPSPECIAL");
const CAPTUREPULLED = require("./CAPTUREPULLED");
const DASH = require("./DASH");
const FORWARDTILT = require("./FORWARDTILT");
const LANDINGFALLSPECIAL = require("./LANDINGFALLSPECIAL");
const STOPCEIL = require("./STOPCEIL");
const UPTILT = require("./UPTILT");
const CAPTUREWAIT = require("./CAPTUREWAIT");
const DEADDOWN = require("./DEADDOWN");
const FURASLEEPEND = require("./FURASLEEPEND");
const MISSFOOT = require("./MISSFOOT");
const TECHB = require("./TECHB");
const WAIT = require("./WAIT");
const CATCHATTACK = require("./CATCHATTACK");
const DEADLEFT = require("./DEADLEFT");
const FURASLEEPLOOP = require("./FURASLEEPLOOP");
const NEUTRALSPECIALAIR = require("./NEUTRALSPECIALAIR");
const TECHF = require("./TECHF");
const WALK = require("./WALK");
const CATCHCUT = require("./CATCHCUT");
const DEADRIGHT = require("./DEADRIGHT");
const FURASLEEPSTART = require("./FURASLEEPSTART");
const NEUTRALSPECIALGROUND = require("./NEUTRALSPECIALGROUND");
const TECHN = require("./TECHN");
const WALKFAST = require("./WALKFAST");
const CATCHWAIT = require("./CATCHWAIT");
const DEADUP = require("./DEADUP");
const GRAB = require("./GRAB");
const NEUTRALSPECIALGROUNDTURN = require("./NEUTRALSPECIALGROUNDTURN");
const TECHU = require("./TECHU");
const WALKMIDDLE = require("./WALKMIDDLE");
const CLIFFATTACKQUICK = require("./CLIFFATTACKQUICK");
const DOWNATTACK = require("./DOWNATTACK");
const GUARD = require("./GUARD");
const OTTOTTO = require("./OTTOTTO");
const THROWBACK = require("./THROWBACK");
const WALKSLOW = require("./WALKSLOW");
const CLIFFATTACKSLOW = require("./CLIFFATTACKSLOW");
const DOWNBOUND = require("./DOWNBOUND");
const GUARDOFF = require("./GUARDOFF");
const OTTOTTOWAIT = require("./OTTOTTOWAIT");
const THROWDOWN = require("./THROWDOWN");
const WALLDAMAGE = require("./WALLDAMAGE");
const CLIFFCATCH = require("./CLIFFCATCH");
const DOWNDAMAGE = require("./DOWNDAMAGE");
const GUARDON = require("./GUARDON");
const PASS = require("./PASS");
const THROWFORWARD = require("./THROWFORWARD");
const WALLTECH = require("./WALLTECH");
const CLIFFESCAPEQUICK = require("./CLIFFESCAPEQUICK");
const DOWNSMASH = require("./DOWNSMASH");
const JAB1 = require("./JAB1");
const REBIRTH = require("./REBIRTH");
const THROWNFOXBACK = require("./THROWNFOXBACK");
const WALLTECHJUMP = require("./WALLTECHJUMP");
const CLIFFESCAPESLOW = require("./CLIFFESCAPESLOW");
const DOWNSPECIALAIR = require("./DOWNSPECIALAIR");
const JAB2 = require("./JAB2");
const REBIRTHWAIT = require("./REBIRTHWAIT");
const THROWNFOXDOWN = require("./THROWNFOXDOWN");
const CLIFFGETUPQUICK = require("./CLIFFGETUPQUICK");
const DOWNSPECIALGROUND = require("./DOWNSPECIALGROUND");
const JUMPAERIAL1 = require("./JUMPAERIAL1");
const RUN = require("./RUN");
const THROWNFOXFORWARD = require("./THROWNFOXFORWARD");
const FURAFURA = require("./FURAFURA");
const REBOUND = require("./REBOUND");
const THROWNFALCOBACK = require("./THROWNFALCOBACK");
const THROWNFALCODOWN = require("./THROWNFALCODOWN");
const THROWNFALCOFORWARD = require("./THROWNFALCOFORWARD");
const THROWNFALCOUP = require("./THROWNFALCOUP");
const THROWNFALCONBACK = require("./THROWNFALCONBACK");
const THROWNFALCONDOWN = require("./THROWNFALCONDOWN");
const THROWNFALCONFORWARD = require("./THROWNFALCONFORWARD");
const THROWNFALCONUP = require("./THROWNFALCONUP");
const APPEAL = require("./APPEAL");
const THROWNFALCONDIVE = require("./THROWNFALCONDIVE");

module.exports = {
  AERIALTURN1: AERIALTURN1,
  CLIFFGETUPSLOW: CLIFFGETUPSLOW,
  DOWNSTANDB: DOWNSTANDB,
  JUMPAERIAL2: JUMPAERIAL2,
  RUNBRAKE: RUNBRAKE,
  THROWNFOXUP: THROWNFOXUP,
  AERIALTURN2: AERIALTURN2,
  CLIFFJUMPQUICK: CLIFFJUMPQUICK,
  DOWNSTANDF: DOWNSTANDF,
  JUMPAERIAL3: JUMPAERIAL3,
  RUNTURN: RUNTURN,
  THROWNMARTHBACK: THROWNMARTHBACK,
  AERIALTURN3: AERIALTURN3,
  CLIFFJUMPSLOW: CLIFFJUMPSLOW,
  DOWNSTANDN: DOWNSTANDN,
  JUMPAERIAL4: JUMPAERIAL4,
  SHIELDBREAKDOWNBOUND: SHIELDBREAKDOWNBOUND,
  THROWNMARTHDOWN: THROWNMARTHDOWN,
  AERIALTURN4: AERIALTURN4,
  CLIFFWAIT: CLIFFWAIT,
  DOWNTILT: DOWNTILT,
  JUMPAERIAL5: JUMPAERIAL5,
  SHIELDBREAKFALL: SHIELDBREAKFALL,
  THROWNMARTHFORWARD: THROWNMARTHFORWARD,
  AERIALTURN5: AERIALTURN5,
  DAMAGEFALL: DAMAGEFALL,
  DOWNWAIT: DOWNWAIT,
  JUMPB: JUMPB,
  SHIELDBREAKFLY: SHIELDBREAKFLY,
  THROWNMARTHUP: THROWNMARTHUP,
  ATTACKAIRB: ATTACKAIRB,
  DAMAGEFLYHI: DAMAGEFLYHI,
  ENTRANCE: ENTRANCE,
  JUMPF: JUMPF,
  SHIELDBREAKSTAND: SHIELDBREAKSTAND,
  THROWNPUFFBACK: THROWNPUFFBACK,
  ATTACKAIRD: ATTACKAIRD,
  DAMAGEFLYLW: DAMAGEFLYLW,
  ESCAPEAIR: ESCAPEAIR,
  KNEEBEND: KNEEBEND,
  SIDESPECIALAIR: SIDESPECIALAIR,
  THROWNPUFFDOWN: THROWNPUFFDOWN,
  ATTACKAIRF: ATTACKAIRF,
  DAMAGEFLYN: DAMAGEFLYN,
  ESCAPEB: ESCAPEB,
  LANDING: LANDING,
  SIDESPECIALGROUND: SIDESPECIALGROUND,
  THROWNPUFFFORWARD: THROWNPUFFFORWARD,
  ATTACKAIRN: ATTACKAIRN,
  DAMAGEFLYTOP: DAMAGEFLYTOP,
  ESCAPEF: ESCAPEF,
  LANDINGATTACKAIRB: LANDINGATTACKAIRB,
  SLEEP: SLEEP,
  THROWNPUFFUP: THROWNPUFFUP,
  ATTACKAIRU: ATTACKAIRU,
  DAMAGEHI1: DAMAGEHI1,
  ESCAPEN: ESCAPEN,
  LANDINGATTACKAIRD: LANDINGATTACKAIRD,
  SMASHTURN: SMASHTURN,
  THROWUP: THROWUP,
  ATTACKDASH: ATTACKDASH,
  DAMAGEHI2: DAMAGEHI2,
  FALL: FALL,
  LANDINGATTACKAIRF: LANDINGATTACKAIRF,
  SQUAT: SQUAT,
  TILTTURN: TILTTURN,
  CAPTURECUT: CAPTURECUT,
  DAMAGEHI3: DAMAGEHI3,
  FALLSPECIAL: FALLSPECIAL,
  LANDINGATTACKAIRN: LANDINGATTACKAIRN,
  SQUATRV: SQUATRV,
  UPSMASH: UPSMASH,
  CAPTUREDAMAGE: CAPTUREDAMAGE,
  DAMAGEN2: DAMAGEN2,
  FORWARDSMASH: FORWARDSMASH,
  LANDINGATTACKAIRU: LANDINGATTACKAIRU,
  SQUATWAIT: SQUATWAIT,
  UPSPECIAL: UPSPECIAL,
  CAPTUREPULLED: CAPTUREPULLED,
  DASH: DASH,
  FORWARDTILT: FORWARDTILT,
  LANDINGFALLSPECIAL: LANDINGFALLSPECIAL,
  STOPCEIL: STOPCEIL,
  UPTILT: UPTILT,
  CAPTUREWAIT: CAPTUREWAIT,
  DEADDOWN: DEADDOWN,
  FURASLEEPEND: FURASLEEPEND,
  MISSFOOT: MISSFOOT,
  TECHB: TECHB,
  WAIT: WAIT,
  CATCHATTACK: CATCHATTACK,
  DEADLEFT: DEADLEFT,
  FURASLEEPLOOP: FURASLEEPLOOP,
  NEUTRALSPECIALAIR: NEUTRALSPECIALAIR,
  TECHF: TECHF,
  WALK: WALK,
  CATCHCUT: CATCHCUT,
  DEADRIGHT: DEADRIGHT,
  FURASLEEPSTART: FURASLEEPSTART,
  NEUTRALSPECIALGROUND: NEUTRALSPECIALGROUND,
  TECHN: TECHN,
  WALKFAST: WALKFAST,
  CATCHWAIT: CATCHWAIT,
  DEADUP: DEADUP,
  GRAB: GRAB,
  NEUTRALSPECIALGROUNDTURN: NEUTRALSPECIALGROUNDTURN,
  TECHU: TECHU,
  WALKMIDDLE: WALKMIDDLE,
  CLIFFATTACKQUICK: CLIFFATTACKQUICK,
  DOWNATTACK: DOWNATTACK,
  GUARD: GUARD,
  OTTOTTO: OTTOTTO,
  THROWBACK: THROWBACK,
  WALKSLOW: WALKSLOW,
  CLIFFATTACKSLOW: CLIFFATTACKSLOW,
  DOWNBOUND: DOWNBOUND,
  GUARDOFF: GUARDOFF,
  OTTOTTOWAIT: OTTOTTOWAIT,
  THROWDOWN: THROWDOWN,
  WALLDAMAGE: WALLDAMAGE,
  CLIFFCATCH: CLIFFCATCH,
  DOWNDAMAGE: DOWNDAMAGE,
  GUARDON: GUARDON,
  PASS: PASS,
  THROWFORWARD: THROWFORWARD,
  WALLTECH: WALLTECH,
  CLIFFESCAPEQUICK: CLIFFESCAPEQUICK,
  DOWNSMASH: DOWNSMASH,
  JAB1: JAB1,
  REBIRTH: REBIRTH,
  THROWNFOXBACK: THROWNFOXBACK,
  WALLTECHJUMP: WALLTECHJUMP,
  CLIFFESCAPESLOW: CLIFFESCAPESLOW,
  DOWNSPECIALAIR: DOWNSPECIALAIR,
  JAB2: JAB2,
  REBIRTHWAIT: REBIRTHWAIT,
  THROWNFOXDOWN: THROWNFOXDOWN,
  CLIFFGETUPQUICK: CLIFFGETUPQUICK,
  DOWNSPECIALGROUND: DOWNSPECIALGROUND,
  JUMPAERIAL1: JUMPAERIAL1,
  RUN: RUN,
  THROWNFOXFORWARD: THROWNFOXFORWARD,
  FURAFURA: FURAFURA,
  REBOUND: REBOUND,
  THROWNFALCOBACK: THROWNFALCOBACK,
  THROWNFALCODOWN: THROWNFALCODOWN,
  THROWNFALCOFORWARD: THROWNFALCOFORWARD,
  THROWNFALCOUP: THROWNFALCOUP,
  THROWNFALCONBACK: THROWNFALCONBACK,
  THROWNFALCONDOWN: THROWNFALCONDOWN,
  THROWNFALCONFORWARD: THROWNFALCONFORWARD,
  THROWNFALCONUP: THROWNFALCONUP,
  APPEAL: APPEAL,
  THROWNFALCONDIVE: THROWNFALCONDIVE
};
