const ATTACKAIRB = require("./ATTACKAIRB");
const DAMAGEN2 = require("./DAMAGEN2");
const FALLAERIAL = require("./FALLAERIAL");
const LANDINGFALLSPECIAL = require("./LANDINGFALLSPECIAL");
const SIDESPECIALGROUND = require("./SIDESPECIALGROUND");
const THROWNFOXUP = require("./THROWNFOXUP");
const ATTACKAIRD = require("./ATTACKAIRD");
const DASH = require("./DASH");
const FALLSPECIAL = require("./FALLSPECIAL");
const MISSFOOT = require("./MISSFOOT");
const SIDESPECIALGROUND2FORWARD = require("./SIDESPECIALGROUND2FORWARD");
const THROWNMARTHBACK = require("./THROWNMARTHBACK");
const ATTACKAIRF = require("./ATTACKAIRF");
const DEADDOWN = require("./DEADDOWN");
const FORWARDSMASH = require("./FORWARDSMASH");
const NEUTRALSPECIALAIR = require("./NEUTRALSPECIALAIR");
const SIDESPECIALGROUND2UP = require("./SIDESPECIALGROUND2UP");
const THROWNMARTHDOWN = require("./THROWNMARTHDOWN");
const ATTACKAIRN = require("./ATTACKAIRN");
const DEADLEFT = require("./DEADLEFT");
const FORWARDTILT = require("./FORWARDTILT");
const NEUTRALSPECIALGROUND = require("./NEUTRALSPECIALGROUND");
const SIDESPECIALGROUND3DOWN = require("./SIDESPECIALGROUND3DOWN");
const THROWNMARTHFORWARD = require("./THROWNMARTHFORWARD");
const ATTACKAIRU = require("./ATTACKAIRU");
const DEADRIGHT = require("./DEADRIGHT");
const FURAFURA = require("./FURAFURA");
const OTTOTTO = require("./OTTOTTO");
const SIDESPECIALGROUND3FORWARD = require("./SIDESPECIALGROUND3FORWARD");
const THROWNMARTHUP = require("./THROWNMARTHUP");
const ATTACKDASH = require("./ATTACKDASH");
const DEADUP = require("./DEADUP");
const FURASLEEPEND = require("./FURASLEEPEND");
const OTTOTTOWAIT = require("./OTTOTTOWAIT");
const SIDESPECIALGROUND3UP = require("./SIDESPECIALGROUND3UP");
const THROWNPUFFBACK = require("./THROWNPUFFBACK");
const CAPTURECUT = require("./CAPTURECUT");
const DOWNATTACK = require("./DOWNATTACK");
const FURASLEEPLOOP = require("./FURASLEEPLOOP");
const PASS = require("./PASS");
const SIDESPECIALGROUND4DOWN = require("./SIDESPECIALGROUND4DOWN");
const THROWNPUFFDOWN = require("./THROWNPUFFDOWN");
const CAPTUREDAMAGE = require("./CAPTUREDAMAGE");
const DOWNBOUND = require("./DOWNBOUND");
const FURASLEEPSTART = require("./FURASLEEPSTART");
const REBIRTH = require("./REBIRTH");
const SIDESPECIALGROUND4FORWARD = require("./SIDESPECIALGROUND4FORWARD");
const THROWNPUFFFORWARD = require("./THROWNPUFFFORWARD");
const CAPTUREPULLED = require("./CAPTUREPULLED");
const DOWNDAMAGE = require("./DOWNDAMAGE");
const GRAB = require("./GRAB");
const REBIRTHWAIT = require("./REBIRTHWAIT");
const SIDESPECIALGROUND4UP = require("./SIDESPECIALGROUND4UP");
const THROWNPUFFUP = require("./THROWNPUFFUP");
const CAPTUREWAIT = require("./CAPTUREWAIT");
const DOWNSMASH = require("./DOWNSMASH");
const GUARD = require("./GUARD");
const REBOUND = require("./REBOUND");
const SLEEP = require("./SLEEP");
const THROWUP = require("./THROWUP");
const CATCHATTACK = require("./CATCHATTACK");
const DOWNSPECIALAIR = require("./DOWNSPECIALAIR");
const GUARDOFF = require("./GUARDOFF");
const RUN = require("./RUN");
const SMASHTURN = require("./SMASHTURN");
const TILTTURN = require("./TILTTURN");
const CATCHCUT = require("./CATCHCUT");
const DOWNSPECIALAIR2 = require("./DOWNSPECIALAIR2");
const GUARDON = require("./GUARDON");
const RUNBRAKE = require("./RUNBRAKE");
const SQUAT = require("./SQUAT");
const UPSMASH = require("./UPSMASH");
const CATCHWAIT = require("./CATCHWAIT");
const DOWNSPECIALGROUND = require("./DOWNSPECIALGROUND");
const JAB1 = require("./JAB1");
const RUNTURN = require("./RUNTURN");
const SQUATRV = require("./SQUATRV");
const UPSPECIAL = require("./UPSPECIAL");
const CLIFFATTACKQUICK = require("./CLIFFATTACKQUICK");
const DOWNSPECIALGROUND2 = require("./DOWNSPECIALGROUND2");
const JAB2 = require("./JAB2");
const SHIELDBREAKDOWNBOUND = require("./SHIELDBREAKDOWNBOUND");
const SQUATWAIT = require("./SQUATWAIT");
const UPTILT = require("./UPTILT");
const CLIFFATTACKSLOW = require("./CLIFFATTACKSLOW");
const DOWNSTANDB = require("./DOWNSTANDB");
const JUMPAERIALB = require("./JUMPAERIALB");
const SHIELDBREAKFALL = require("./SHIELDBREAKFALL");
const STOPCEIL = require("./STOPCEIL");
const WAIT = require("./WAIT");
const CLIFFCATCH = require("./CLIFFCATCH");
const DOWNSTANDF = require("./DOWNSTANDF");
const JUMPAERIALF = require("./JUMPAERIALF");
const SHIELDBREAKSTAND = require("./SHIELDBREAKSTAND");
const TECHB = require("./TECHB");
const WALK = require("./WALK");
const CLIFFESCAPEQUICK = require("./CLIFFESCAPEQUICK");
const DOWNSTANDN = require("./DOWNSTANDN");
const JUMPB = require("./JUMPB");
const SIDESPECIALAIR = require("./SIDESPECIALAIR");
const TECHF = require("./TECHF");
const WALLDAMAGE = require("./WALLDAMAGE");
const CLIFFESCAPESLOW = require("./CLIFFESCAPESLOW");
const DOWNTILT = require("./DOWNTILT");
const JUMPF = require("./JUMPF");
const SIDESPECIALAIR2FORWARD = require("./SIDESPECIALAIR2FORWARD");
const TECHN = require("./TECHN");
const WALLJUMP = require("./WALLJUMP");
const CLIFFGETUPQUICK = require("./CLIFFGETUPQUICK");
const DOWNWAIT = require("./DOWNWAIT");
const KNEEBEND = require("./KNEEBEND");
const SIDESPECIALAIR2UP = require("./SIDESPECIALAIR2UP");
const TECHU = require("./TECHU");
const WALLTECH = require("./WALLTECH");
const CLIFFGETUPSLOW = require("./CLIFFGETUPSLOW");
const ENTRANCE = require("./ENTRANCE");
const LANDING = require("./LANDING");
const SIDESPECIALAIR3DOWN = require("./SIDESPECIALAIR3DOWN");
const THROWBACK = require("./THROWBACK");
const WALLTECHJUMP = require("./WALLTECHJUMP");
const CLIFFJUMPQUICK = require("./CLIFFJUMPQUICK");
const ESCAPEAIR = require("./ESCAPEAIR");
const LANDINGATTACKAIRB = require("./LANDINGATTACKAIRB");
const SIDESPECIALAIR3FORWARD = require("./SIDESPECIALAIR3FORWARD");
const THROWDOWN = require("./THROWDOWN");
const CLIFFJUMPSLOW = require("./CLIFFJUMPSLOW");
const ESCAPEB = require("./ESCAPEB");
const LANDINGATTACKAIRD = require("./LANDINGATTACKAIRD");
const SIDESPECIALAIR3UP = require("./SIDESPECIALAIR3UP");
const THROWFORWARD = require("./THROWFORWARD");
const CLIFFWAIT = require("./CLIFFWAIT");
const ESCAPEF = require("./ESCAPEF");
const LANDINGATTACKAIRF = require("./LANDINGATTACKAIRF");
const SIDESPECIALAIR4DOWN = require("./SIDESPECIALAIR4DOWN");
const THROWNFOXBACK = require("./THROWNFOXBACK");
const DAMAGEFALL = require("./DAMAGEFALL");
const ESCAPEN = require("./ESCAPEN");
const LANDINGATTACKAIRN = require("./LANDINGATTACKAIRN");
const SIDESPECIALAIR4FORWARD = require("./SIDESPECIALAIR4FORWARD");
const THROWNFOXDOWN = require("./THROWNFOXDOWN");
const DAMAGEFLYN = require("./DAMAGEFLYN");
const FALL = require("./FALL");
const LANDINGATTACKAIRU = require("./LANDINGATTACKAIRU");
const SIDESPECIALAIR4UP = require("./SIDESPECIALAIR4UP");
const THROWNFOXFORWARD = require("./THROWNFOXFORWARD");
const THROWNFALCOBACK = require("./THROWNFALCOBACK.js");
const THROWNFALCODOWN = require("./THROWNFALCODOWN.js");
const THROWNFALCOFORWARD = require("./THROWNFALCOFORWARD.js");
const THROWNFALCOUP = require("./THROWNFALCOUP.js");
const THROWNFALCONBACK = require("./THROWNFALCONBACK");
const THROWNFALCONDOWN = require("./THROWNFALCONDOWN");
const THROWNFALCONFORWARD = require("./THROWNFALCONFORWARD");
const THROWNFALCONUP = require("./THROWNFALCONUP");
const APPEAL = require("./APPEAL.js");
const THROWNFALCONDIVE = require("./THROWNFALCONDIVE");

module.exports = {
  ATTACKAIRB: ATTACKAIRB,
  DAMAGEN2: DAMAGEN2,
  FALLAERIAL: FALLAERIAL,
  LANDINGFALLSPECIAL: LANDINGFALLSPECIAL,
  SIDESPECIALGROUND: SIDESPECIALGROUND,
  THROWNFOXUP: THROWNFOXUP,
  ATTACKAIRD: ATTACKAIRD,
  DASH: DASH,
  FALLSPECIAL: FALLSPECIAL,
  MISSFOOT: MISSFOOT,
  SIDESPECIALGROUND2FORWARD: SIDESPECIALGROUND2FORWARD,
  THROWNMARTHBACK: THROWNMARTHBACK,
  ATTACKAIRF: ATTACKAIRF,
  DEADDOWN: DEADDOWN,
  FORWARDSMASH: FORWARDSMASH,
  NEUTRALSPECIALAIR: NEUTRALSPECIALAIR,
  SIDESPECIALGROUND2UP: SIDESPECIALGROUND2UP,
  THROWNMARTHDOWN: THROWNMARTHDOWN,
  ATTACKAIRN: ATTACKAIRN,
  DEADLEFT: DEADLEFT,
  FORWARDTILT: FORWARDTILT,
  NEUTRALSPECIALGROUND: NEUTRALSPECIALGROUND,
  SIDESPECIALGROUND3DOWN: SIDESPECIALGROUND3DOWN,
  THROWNMARTHFORWARD: THROWNMARTHFORWARD,
  ATTACKAIRU: ATTACKAIRU,
  DEADRIGHT: DEADRIGHT,
  FURAFURA: FURAFURA,
  OTTOTTO: OTTOTTO,
  SIDESPECIALGROUND3FORWARD: SIDESPECIALGROUND3FORWARD,
  THROWNMARTHUP: THROWNMARTHUP,
  ATTACKDASH: ATTACKDASH,
  DEADUP: DEADUP,
  FURASLEEPEND: FURASLEEPEND,
  OTTOTTOWAIT: OTTOTTOWAIT,
  SIDESPECIALGROUND3UP: SIDESPECIALGROUND3UP,
  THROWNPUFFBACK: THROWNPUFFBACK,
  CAPTURECUT: CAPTURECUT,
  DOWNATTACK: DOWNATTACK,
  FURASLEEPLOOP: FURASLEEPLOOP,
  PASS: PASS,
  SIDESPECIALGROUND4DOWN: SIDESPECIALGROUND4DOWN,
  THROWNPUFFDOWN: THROWNPUFFDOWN,
  CAPTUREDAMAGE: CAPTUREDAMAGE,
  DOWNBOUND: DOWNBOUND,
  FURASLEEPSTART: FURASLEEPSTART,
  REBIRTH: REBIRTH,
  SIDESPECIALGROUND4FORWARD: SIDESPECIALGROUND4FORWARD,
  THROWNPUFFFORWARD: THROWNPUFFFORWARD,
  CAPTUREPULLED: CAPTUREPULLED,
  DOWNDAMAGE: DOWNDAMAGE,
  GRAB: GRAB,
  REBIRTHWAIT: REBIRTHWAIT,
  SIDESPECIALGROUND4UP: SIDESPECIALGROUND4UP,
  THROWNPUFFUP: THROWNPUFFUP,
  CAPTUREWAIT: CAPTUREWAIT,
  DOWNSMASH: DOWNSMASH,
  GUARD: GUARD,
  REBOUND: REBOUND,
  SLEEP: SLEEP,
  THROWUP: THROWUP,
  CATCHATTACK: CATCHATTACK,
  DOWNSPECIALAIR: DOWNSPECIALAIR,
  GUARDOFF: GUARDOFF,
  RUN: RUN,
  SMASHTURN: SMASHTURN,
  TILTTURN: TILTTURN,
  CATCHCUT: CATCHCUT,
  DOWNSPECIALAIR2: DOWNSPECIALAIR2,
  GUARDON: GUARDON,
  RUNBRAKE: RUNBRAKE,
  SQUAT: SQUAT,
  UPSMASH: UPSMASH,
  CATCHWAIT: CATCHWAIT,
  DOWNSPECIALGROUND: DOWNSPECIALGROUND,
  JAB1: JAB1,
  RUNTURN: RUNTURN,
  SQUATRV: SQUATRV,
  UPSPECIAL: UPSPECIAL,
  CLIFFATTACKQUICK: CLIFFATTACKQUICK,
  DOWNSPECIALGROUND2: DOWNSPECIALGROUND2,
  JAB2: JAB2,
  SHIELDBREAKDOWNBOUND: SHIELDBREAKDOWNBOUND,
  SQUATWAIT: SQUATWAIT,
  UPTILT: UPTILT,
  CLIFFATTACKSLOW: CLIFFATTACKSLOW,
  DOWNSTANDB: DOWNSTANDB,
  JUMPAERIALB: JUMPAERIALB,
  SHIELDBREAKFALL: SHIELDBREAKFALL,
  STOPCEIL: STOPCEIL,
  WAIT: WAIT,
  CLIFFCATCH: CLIFFCATCH,
  DOWNSTANDF: DOWNSTANDF,
  JUMPAERIALF: JUMPAERIALF,
  SHIELDBREAKSTAND: SHIELDBREAKSTAND,
  TECHB: TECHB,
  WALK: WALK,
  CLIFFESCAPEQUICK: CLIFFESCAPEQUICK,
  DOWNSTANDN: DOWNSTANDN,
  JUMPB: JUMPB,
  SIDESPECIALAIR: SIDESPECIALAIR,
  TECHF: TECHF,
  WALLDAMAGE: WALLDAMAGE,
  CLIFFESCAPESLOW: CLIFFESCAPESLOW,
  DOWNTILT: DOWNTILT,
  JUMPF: JUMPF,
  SIDESPECIALAIR2FORWARD: SIDESPECIALAIR2FORWARD,
  TECHN: TECHN,
  WALLJUMP: WALLJUMP,
  CLIFFGETUPQUICK: CLIFFGETUPQUICK,
  DOWNWAIT: DOWNWAIT,
  KNEEBEND: KNEEBEND,
  SIDESPECIALAIR2UP: SIDESPECIALAIR2UP,
  TECHU: TECHU,
  WALLTECH: WALLTECH,
  CLIFFGETUPSLOW: CLIFFGETUPSLOW,
  ENTRANCE: ENTRANCE,
  LANDING: LANDING,
  SIDESPECIALAIR3DOWN: SIDESPECIALAIR3DOWN,
  THROWBACK: THROWBACK,
  WALLTECHJUMP: WALLTECHJUMP,
  CLIFFJUMPQUICK: CLIFFJUMPQUICK,
  ESCAPEAIR: ESCAPEAIR,
  LANDINGATTACKAIRB: LANDINGATTACKAIRB,
  SIDESPECIALAIR3FORWARD: SIDESPECIALAIR3FORWARD,
  THROWDOWN: THROWDOWN,
  CLIFFJUMPSLOW: CLIFFJUMPSLOW,
  ESCAPEB: ESCAPEB,
  LANDINGATTACKAIRD: LANDINGATTACKAIRD,
  SIDESPECIALAIR3UP: SIDESPECIALAIR3UP,
  THROWFORWARD: THROWFORWARD,
  CLIFFWAIT: CLIFFWAIT,
  ESCAPEF: ESCAPEF,
  LANDINGATTACKAIRF: LANDINGATTACKAIRF,
  SIDESPECIALAIR4DOWN: SIDESPECIALAIR4DOWN,
  THROWNFOXBACK: THROWNFOXBACK,
  DAMAGEFALL: DAMAGEFALL,
  ESCAPEN: ESCAPEN,
  LANDINGATTACKAIRN: LANDINGATTACKAIRN,
  SIDESPECIALAIR4FORWARD: SIDESPECIALAIR4FORWARD,
  THROWNFOXDOWN: THROWNFOXDOWN,
  DAMAGEFLYN: DAMAGEFLYN,
  FALL: FALL,
  LANDINGATTACKAIRU: LANDINGATTACKAIRU,
  SIDESPECIALAIR4UP: SIDESPECIALAIR4UP,
  THROWNFOXFORWARD: THROWNFOXFORWARD,
  THROWNFALCOBACK: THROWNFALCOBACK,
  THROWNFALCODOWN: THROWNFALCODOWN,
  THROWNFALCOFORWARD: THROWNFALCOFORWARD,
  THROWNFALCOUP: THROWNFALCOUP,
  THROWNFALCONBACK: THROWNFALCONBACK,
  THROWNFALCONDOWN: THROWNFALCONDOWN,
  THROWNFALCONFORWARD: THROWNFALCONFORWARD,
  THROWNFALCONUP: THROWNFALCONUP,
  APPEAL: APPEAL,
  THROWNFALCONDIVE: THROWNFALCONDIVE
};
