const CAPTUREDAMAGE = require("./CAPTUREDAMAGE");
const CAPTUREPULLED = require("./CAPTUREPULLED");
const CATCHATTACK = require("./CATCHATTACK");
const CLIFFCATCH = require("./CLIFFCATCH");
const DOWNDAMAGE = require("./DOWNDAMAGE");
const FALL = require("./FALL");
const FALLSPECIAL = require("./FALLSPECIAL");
const FALLAERIAL = require("./FALLAERIAL");
const GUARD = require("./GUARD");
const FURASLEEPLOOP = require("./FURASLEEPLOOP");
const KNEEBEND = require("./KNEEBEND");
const GUARDOFF = require("./GUARDOFF");
const GUARDON = require("./GUARDON");
const LANDINGATTACKAIRB = require("./LANDINGATTACKAIRB");
const LANDINGATTACKAIRN = require("./LANDINGATTACKAIRN");
const OTTOTTO = require("./OTTOTTO");
const SMASHTURN = require("./SMASHTURN");
const LANDINGATTACKAIRF = require("./LANDINGATTACKAIRF");
const LANDINGATTACKAIRU = require("./LANDINGATTACKAIRU");
const LANDINGATTACKAIRD = require("./LANDINGATTACKAIRD");
const STOPCEIL = require("./STOPCEIL");
const REBOUND = require("./REBOUND");
const SQUATRV = require("./SQUATRV");
const SQUAT = require("./SQUAT");
const THROWNFALCONUP = require("./THROWNFALCONUP");
const THROWNFALCOBACK = require("./THROWNFALCOBACK");
const THROWNFALCONDOWN = require("./THROWNFALCONDOWN");
const THROWNFALCOUP = require("./THROWNFALCOUP");
const THROWNFALCONFORWARD = require("./THROWNFALCONFORWARD");
const THROWNMARTHBACK = require("./THROWNMARTHBACK");
const THROWNFALCONBACK = require("./THROWNFALCONBACK");
const THROWNFALCOFORWARD = require("./THROWNFALCOFORWARD");
const THROWNFOXUP = require("./THROWNFOXUP");
const TILTTURN = require("./TILTTURN");
const THROWNMARTHFORWARD = require("./THROWNMARTHFORWARD");
const THROWNPUFFFORWARD = require("./THROWNPUFFFORWARD");
const THROWNPUFFUP = require("./THROWNPUFFUP");
const THROWNMARTHDOWN = require("./THROWNMARTHDOWN");
const THROWNFOXFORWARD = require("./THROWNFOXFORWARD");
const THROWNFOXBACK = require("./THROWNFOXBACK");
const THROWNSHEIKBACK = require("./THROWNSHEIKBACK");
const THROWNMARTHUP = require("./THROWNMARTHUP");
const ATTACKAIRD = require("./ATTACKAIRD");
const UPSPECIALCATCH = require("./UPSPECIALCATCH");
const ATTACKDASH = require("./ATTACKDASH");
const CAPTUREWAIT = require("./CAPTUREWAIT");
const CATCHCUT = require("./CATCHCUT");
const DASH = require("./DASH");
const DAMAGEN2 = require("./DAMAGEN2");
const DOWNSTANDN = require("./DOWNSTANDN");
const DOWNBOUND = require("./DOWNBOUND");
const DOWNSTANDF = require("./DOWNSTANDF");
const ESCAPEN = require("./ESCAPEN");
const JAB2 = require("./JAB2");
const THROWNSHEIKUP = require("./THROWNSHEIKUP");
const DOWNSPECIALAIRENDAIR = require("./DOWNSPECIALAIRENDAIR");
const ATTACKAIRF = require("./ATTACKAIRF");
const DOWNSPECIALAIR = require("./DOWNSPECIALAIR");
const DAMAGEFLYN = require("./DAMAGEFLYN");
const JAB3 = require("./JAB3");
const ATTACKAIRU = require("./ATTACKAIRU");
const ATTACKAIRB = require("./ATTACKAIRB");
const CLIFFJUMPQUICK = require("./CLIFFJUMPQUICK");
const DOWNSPECIALGROUNDENDAIR = require("./DOWNSPECIALGROUNDENDAIR");
const CAPTURECUT = require("./CAPTURECUT");
const DOWNTILT = require("./DOWNTILT");
const CATCHWAIT = require("./CATCHWAIT");
const CLIFFGETUPQUICK = require("./CLIFFGETUPQUICK");
const ESCAPEB = require("./ESCAPEB");
const ESCAPEF = require("./ESCAPEF");
const DOWNSTANDB = require("./DOWNSTANDB");
const DAMAGEFALL = require("./DAMAGEFALL");
const JUMPF = require("./JUMPF");
const JAB1 = require("./JAB1");
const FURASLEEPSTART = require("./FURASLEEPSTART");
const JUMPAERIALB = require("./JUMPAERIALB");
const FORWARDTILT = require("./FORWARDTILT");
const LANDING = require("./LANDING");
const MISSFOOT = require("./MISSFOOT");
const JUMPAERIALF = require("./JUMPAERIALF");
const GRAB = require("./GRAB");
const UPTILT = require("./UPTILT");
const THROWDOWN = require("./THROWDOWN");
const TECHU = require("./TECHU");
const TECHB = require("./TECHB");
const THROWFORWARD = require("./THROWFORWARD");
const WALK = require("./WALK");
const PASS = require("./PASS");
const WALLJUMP = require("./WALLJUMP");
const TECHN = require("./TECHN");
const TECHF = require("./TECHF");
const WALLTECH = require("./WALLTECH");
const RUN = require("./RUN");
const RUNBRAKE = require("./RUNBRAKE");
const WALLTECHJUMP = require("./WALLTECHJUMP");
const THROWNFALCODOWN = require("./THROWNFALCODOWN");
const RUNTURN = require("./RUNTURN");
const THROWNFOXDOWN = require("./THROWNFOXDOWN");
const THROWNSHEIKFORWARD = require("./THROWNSHEIKFORWARD");
const THROWNSHEIKDOWN = require("./THROWNSHEIKDOWN");
const THROWNPUFFBACK = require("./THROWNPUFFBACK");
const DOWNSPECIALGROUND = require("./DOWNSPECIALGROUND");
const DOWNSPECIALGROUNDENDGROUND = require("./DOWNSPECIALGROUNDENDGROUND");
const ATTACKAIRN = require("./ATTACKAIRN");
const SIDESPECIALGROUNDHIT = require("./SIDESPECIALGROUNDHIT");
const CLIFFATTACKQUICK = require("./CLIFFATTACKQUICK");
const CLIFFESCAPEQUICK = require("./CLIFFESCAPEQUICK");
const CLIFFJUMPSLOW = require("./CLIFFJUMPSLOW");
const CLIFFGETUPSLOW = require("./CLIFFGETUPSLOW");
const DOWNATTACK = require("./DOWNATTACK");
const DOWNSMASH = require("./DOWNSMASH");
const DOWNWAIT = require("./DOWNWAIT");
const CLIFFWAIT = require("./CLIFFWAIT");
const ESCAPEAIR = require("./ESCAPEAIR");
const APPEAL = require("./APPEAL");
const FURASLEEPEND = require("./FURASLEEPEND");
const JUMPB = require("./JUMPB");
const DOWNSPECIALAIRENDGROUND = require("./DOWNSPECIALAIRENDGROUND");
const UPSMASH = require("./UPSMASH");
const THROWBACK = require("./THROWBACK");
const WALLDAMAGE = require("./WALLDAMAGE");
const THROWUP = require("./THROWUP");
const THROWNPUFFDOWN = require("./THROWNPUFFDOWN");
const CLIFFATTACKSLOW = require("./CLIFFATTACKSLOW");
const CLIFFESCAPESLOW = require("./CLIFFESCAPESLOW");
const FORWARDSMASH = require("./FORWARDSMASH");
const SIDESPECIALAIRHIT = require("./SIDESPECIALAIRHIT");
const WAIT = require("./WAIT");
const SQUATWAIT = require("./SQUATWAIT");
const SIDESPECIALGROUND = require("./SIDESPECIALGROUND");
const UPSPECIAL = require("./UPSPECIAL");
const UPSPECIALTHROW = require("./UPSPECIALTHROW");
const OTTOTTOWAIT = require("./OTTOTTOWAIT");
const SIDESPECIALAIR = require("./SIDESPECIALAIR");
const FURAFURA = require("./FURAFURA");
const NEUTRALSPECIALGROUND = require("./NEUTRALSPECIALGROUND");
const NEUTRALSPECIALAIR = require("./NEUTRALSPECIALAIR");
const ENTRANCE = require("./ENTRANCE");
const REBIRTH = require("./REBIRTH");
const REBIRTHWAIT = require("./REBIRTHWAIT");
const LANDINGFALLSPECIAL = require("./LANDINGFALLSPECIAL");
const THROWNFALCONDIVE = require("./THROWNFALCONDIVE");
const SHIELDBREAKSTAND = require("./SHIELDBREAKSTAND");
const SHIELDBREAKFALL = require("./SHIELDBREAKFALL");
const SHIELDBREAKDOWNBOUND = require("./SHIELDBREAKDOWNBOUND");

module.exports = {
    CAPTUREDAMAGE: CAPTUREDAMAGE,
    CAPTUREPULLED: CAPTUREPULLED,
    CATCHATTACK: CATCHATTACK,
    CLIFFCATCH: CLIFFCATCH,
    DOWNDAMAGE: DOWNDAMAGE,
    FALL: FALL,
    FALLSPECIAL: FALLSPECIAL,
    FALLAERIAL: FALLAERIAL,
    GUARD: GUARD,
    FURASLEEPLOOP: FURASLEEPLOOP,
    KNEEBEND: KNEEBEND,
    GUARDOFF: GUARDOFF,
    GUARDON: GUARDON,
    LANDINGATTACKAIRB: LANDINGATTACKAIRB,
    LANDINGATTACKAIRN: LANDINGATTACKAIRN,
    OTTOTTO: OTTOTTO,
    SMASHTURN: SMASHTURN,
    LANDINGATTACKAIRF: LANDINGATTACKAIRF,
    LANDINGATTACKAIRU: LANDINGATTACKAIRU,
    LANDINGATTACKAIRD: LANDINGATTACKAIRD,
    STOPCEIL: STOPCEIL,
    REBOUND: REBOUND,
    SQUATRV: SQUATRV,
    SQUAT: SQUAT,
    THROWNFALCONUP: THROWNFALCONUP,
    THROWNFALCOBACK: THROWNFALCOBACK,
    THROWNFALCONDOWN: THROWNFALCONDOWN,
    THROWNFALCOUP: THROWNFALCOUP,
    THROWNFALCONFORWARD: THROWNFALCONFORWARD,
    THROWNMARTHBACK: THROWNMARTHBACK,
    THROWNFALCONBACK: THROWNFALCONBACK,
    THROWNFALCOFORWARD: THROWNFALCOFORWARD,
    THROWNFOXUP: THROWNFOXUP,
    TILTTURN: TILTTURN,
    THROWNMARTHFORWARD: THROWNMARTHFORWARD,
    THROWNPUFFFORWARD: THROWNPUFFFORWARD,
    THROWNPUFFUP: THROWNPUFFUP,
    THROWNMARTHDOWN: THROWNMARTHDOWN,
    THROWNFOXFORWARD: THROWNFOXFORWARD,
    THROWNFOXBACK: THROWNFOXBACK,
    THROWNSHEIKBACK: THROWNSHEIKBACK,
    THROWNMARTHUP: THROWNMARTHUP,
    ATTACKAIRD: ATTACKAIRD,
    UPSPECIALCATCH: UPSPECIALCATCH,
    ATTACKDASH: ATTACKDASH,
    CAPTUREWAIT: CAPTUREWAIT,
    CATCHCUT: CATCHCUT,
    DASH: DASH,
    DAMAGEN2: DAMAGEN2,
    DOWNSTANDN: DOWNSTANDN,
    DOWNBOUND: DOWNBOUND,
    DOWNSTANDF: DOWNSTANDF,
    ESCAPEN: ESCAPEN,
    JAB2: JAB2,
    THROWNSHEIKUP: THROWNSHEIKUP,
    DOWNSPECIALAIRENDAIR: DOWNSPECIALAIRENDAIR,
    ATTACKAIRF: ATTACKAIRF,
    DOWNSPECIALAIR: DOWNSPECIALAIR,
    DAMAGEFLYN: DAMAGEFLYN,
    JAB3: JAB3,
    ATTACKAIRU: ATTACKAIRU,
    ATTACKAIRB: ATTACKAIRB,
    CLIFFJUMPQUICK: CLIFFJUMPQUICK,
    DOWNSPECIALGROUNDENDAIR: DOWNSPECIALGROUNDENDAIR,
    CAPTURECUT: CAPTURECUT,
    DOWNTILT: DOWNTILT,
    CATCHWAIT: CATCHWAIT,
    CLIFFGETUPQUICK: CLIFFGETUPQUICK,
    ESCAPEB: ESCAPEB,
    ESCAPEF: ESCAPEF,
    DOWNSTANDB: DOWNSTANDB,
    DAMAGEFALL: DAMAGEFALL,
    JUMPF: JUMPF,
    JAB1: JAB1,
    FURASLEEPSTART: FURASLEEPSTART,
    JUMPAERIALB: JUMPAERIALB,
    FORWARDTILT: FORWARDTILT,
    LANDING: LANDING,
    MISSFOOT: MISSFOOT,
    JUMPAERIALF: JUMPAERIALF,
    GRAB: GRAB,
    UPTILT: UPTILT,
    THROWDOWN: THROWDOWN,
    TECHU: TECHU,
    TECHB: TECHB,
    THROWFORWARD: THROWFORWARD,
    WALK: WALK,
    PASS: PASS,
    WALLJUMP: WALLJUMP,
    TECHN: TECHN,
    TECHF: TECHF,
    WALLTECH: WALLTECH,
    RUN: RUN,
    RUNBRAKE: RUNBRAKE,
    WALLTECHJUMP: WALLTECHJUMP,
    THROWNFALCODOWN: THROWNFALCODOWN,
    RUNTURN: RUNTURN,
    THROWNFOXDOWN: THROWNFOXDOWN,
    THROWNSHEIKFORWARD: THROWNSHEIKFORWARD,
    THROWNSHEIKDOWN: THROWNSHEIKDOWN,
    THROWNPUFFBACK: THROWNPUFFBACK,
    DOWNSPECIALGROUND: DOWNSPECIALGROUND,
    DOWNSPECIALGROUNDENDGROUND: DOWNSPECIALGROUNDENDGROUND,
    ATTACKAIRN: ATTACKAIRN,
    SIDESPECIALGROUNDHIT: SIDESPECIALGROUNDHIT,
    CLIFFATTACKQUICK: CLIFFATTACKQUICK,
    CLIFFESCAPEQUICK: CLIFFESCAPEQUICK,
    CLIFFJUMPSLOW: CLIFFJUMPSLOW,
    CLIFFGETUPSLOW: CLIFFGETUPSLOW,
    DOWNATTACK: DOWNATTACK,
    DOWNSMASH: DOWNSMASH,
    DOWNWAIT: DOWNWAIT,
    CLIFFWAIT: CLIFFWAIT,
    ESCAPEAIR: ESCAPEAIR,
    APPEAL: APPEAL,
    FURASLEEPEND: FURASLEEPEND,
    JUMPB: JUMPB,
    DOWNSPECIALAIRENDGROUND: DOWNSPECIALAIRENDGROUND,
    UPSMASH: UPSMASH,
    THROWBACK: THROWBACK,
    WALLDAMAGE: WALLDAMAGE,
    THROWUP: THROWUP,
    THROWNPUFFDOWN: THROWNPUFFDOWN,
    CLIFFATTACKSLOW: CLIFFATTACKSLOW,
    CLIFFESCAPESLOW: CLIFFESCAPESLOW,
    FORWARDSMASH: FORWARDSMASH,
    SIDESPECIALAIRHIT: SIDESPECIALAIRHIT,
    WAIT: WAIT,
    SQUATWAIT: SQUATWAIT,
    SIDESPECIALGROUND: SIDESPECIALGROUND,
    UPSPECIAL: UPSPECIAL,
    UPSPECIALTHROW: UPSPECIALTHROW,
    OTTOTTOWAIT: OTTOTTOWAIT,
    SIDESPECIALAIR: SIDESPECIALAIR,
    FURAFURA: FURAFURA,
    NEUTRALSPECIALGROUND: NEUTRALSPECIALGROUND,
    NEUTRALSPECIALAIR: NEUTRALSPECIALAIR,
    ENTRANCE: ENTRANCE,
    REBIRTH: REBIRTH,
    REBIRTHWAIT: REBIRTHWAIT,
    LANDINGFALLSPECIAL: LANDINGFALLSPECIAL,
    THROWNFALCONDIVE: THROWNFALCONDIVE,
    SHIELDBREAKDOWNBOUND: SHIELDBREAKDOWNBOUND,
    SHIELDBREAKFALL: SHIELDBREAKFALL,
    SHIELDBREAKSTAND: SHIELDBREAKSTAND
}