const LargeMap = require('../../../node_modules/large-map/lib');

const ATTACKAIRB = require("./ATTACKAIRB.js");
const CLIFFESCAPESLOW = require("./CLIFFESCAPESLOW.js");
const DOWNSMASH = require("./DOWNSMASH.js");
const FALLSPECIAL = require("./FALLSPECIAL.js");
const JUMPB = require("./JUMPB.js");
const REBIRTHWAIT = require("./REBIRTHWAIT.js");
const TECHF = require("./TECHF.js");
const THROWNPUFFUP = require("./THROWNPUFFUP.js");
const ATTACKAIRD = require("./ATTACKAIRD.js");
const CLIFFGETUPQUICK = require("./CLIFFGETUPQUICK.js");
const DOWNSPECIALAIR = require("./DOWNSPECIALAIR.js");
const FIREFOXBOUNCE = require("./FIREFOXBOUNCE.js");
const JUMPF = require("./JUMPF.js");
const REBOUND = require("./REBOUND.js");
const TECHN = require("./TECHN.js");
const THROWUP = require("./THROWUP.js");
const ATTACKAIRF = require("./ATTACKAIRF.js");
const CLIFFGETUPSLOW = require("./CLIFFGETUPSLOW.js");
const DOWNSPECIALGROUND = require("./DOWNSPECIALGROUND.js");
const FORWARDSMASH = require("./FORWARDSMASH.js");
const KNEEBEND = require("./KNEEBEND.js");
const RUN = require("./RUN.js");
const TECHU = require("./TECHU.js");
const TILTTURN = require("./TILTTURN.js");
const ATTACKAIRN = require("./ATTACKAIRN.js");
const CLIFFJUMPQUICK = require("./CLIFFJUMPQUICK.js");
const DOWNSTANDB = require("./DOWNSTANDB.js");
const FORWARDTILT = require("./FORWARDTILT.js");
const LANDING = require("./LANDING.js");
const RUNBRAKE = require("./RUNBRAKE.js");
const THROWBACK = require("./THROWBACK.js");
const UPSMASH = require("./UPSMASH.js");
const ATTACKAIRU = require("./ATTACKAIRU.js");
const CLIFFJUMPSLOW = require("./CLIFFJUMPSLOW.js");
const DOWNSTANDF = require("./DOWNSTANDF.js");
const FURAFURA = require("./FURAFURA.js");
const LANDINGATTACKAIRB = require("./LANDINGATTACKAIRB.js");
const RUNTURN = require("./RUNTURN.js");
const THROWDOWN = require("./THROWDOWN.js");
const UPSPECIALCHARGE = require("./UPSPECIALCHARGE.js");
const ATTACKDASH = require("./ATTACKDASH.js");
const CLIFFWAIT = require("./CLIFFWAIT.js");
const DOWNSTANDN = require("./DOWNSTANDN.js");
const FURASLEEPEND = require("./FURASLEEPEND.js");
const LANDINGATTACKAIRD = require("./LANDINGATTACKAIRD.js");
const SHIELDBREAKDOWNBOUND = require("./SHIELDBREAKDOWNBOUND.js");
const THROWFORWARD = require("./THROWFORWARD.js");
const UPSPECIALLAUNCH = require("./UPSPECIALLAUNCH.js");
const CAPTURECUT = require("./CAPTURECUT.js");
const DAMAGEFALL = require("./DAMAGEFALL.js");
const DOWNTILT = require("./DOWNTILT.js");
const FURASLEEPLOOP = require("./FURASLEEPLOOP.js");
const LANDINGATTACKAIRF = require("./LANDINGATTACKAIRF.js");
const SHIELDBREAKFALL = require("./SHIELDBREAKFALL.js");
const THROWNFOXBACK = require("./THROWNFOXBACK.js");
const UPTILT = require("./UPTILT.js");
const CAPTUREDAMAGE = require("./CAPTUREDAMAGE.js");
const DAMAGEFLYN = require("./DAMAGEFLYN.js");
const DOWNWAIT = require("./DOWNWAIT.js");
const FURASLEEPSTART = require("./FURASLEEPSTART.js");
const LANDINGATTACKAIRN = require("./LANDINGATTACKAIRN.js");
const SHIELDBREAKSTAND = require("./SHIELDBREAKSTAND.js");
const THROWNFOXDOWN = require("./THROWNFOXDOWN.js");
const WAIT = require("./WAIT.js");
const CAPTUREPULLED = require("./CAPTUREPULLED.js");
const DAMAGEN2 = require("./DAMAGEN2.js");
const ENTRANCE = require("./ENTRANCE.js");
const GRAB = require("./GRAB.js");
const LANDINGATTACKAIRU = require("./LANDINGATTACKAIRU.js");
const SIDESPECIALAIR = require("./SIDESPECIALAIR.js");
const THROWNFOXFORWARD = require("./THROWNFOXFORWARD.js");
const WALK = require("./WALK.js");
const CAPTUREWAIT = require("./CAPTUREWAIT.js");
const DASH = require("./DASH.js");
const ESCAPEAIR = require("./ESCAPEAIR.js");
const GUARD = require("./GUARD.js");
const LANDINGFALLSPECIAL = require("./LANDINGFALLSPECIAL.js");
const SIDESPECIALGROUND = require("./SIDESPECIALGROUND.js");
const THROWNFOXUP = require("./THROWNFOXUP.js");
const WALLDAMAGE = require("./WALLDAMAGE.js");
const CATCHATTACK = require("./CATCHATTACK.js");
const DEADDOWN = require("./DEADDOWN.js");
const ESCAPEB = require("./ESCAPEB.js");
const GUARDOFF = require("./GUARDOFF.js");
const MISSFOOT = require("./MISSFOOT.js");
const SLEEP = require("./SLEEP.js");
const THROWNMARTHBACK = require("./THROWNMARTHBACK.js");
const WALLJUMP = require("./WALLJUMP.js");
const CATCHCUT = require("./CATCHCUT.js");
const DEADLEFT = require("./DEADLEFT.js");
const ESCAPEF = require("./ESCAPEF.js");
const GUARDON = require("./GUARDON.js");
const NEUTRALSPECIALAIR = require("./NEUTRALSPECIALAIR.js");
const SMASHTURN = require("./SMASHTURN.js");
const THROWNMARTHDOWN = require("./THROWNMARTHDOWN.js");
const WALLTECH = require("./WALLTECH.js");
const CATCHWAIT = require("./CATCHWAIT.js");
const DEADRIGHT = require("./DEADRIGHT.js");
const ESCAPEN = require("./ESCAPEN.js");
const JAB1 = require("./JAB1.js");
const NEUTRALSPECIALGROUND = require("./NEUTRALSPECIALGROUND.js");
const SQUAT = require("./SQUAT.js");
const THROWNMARTHFORWARD = require("./THROWNMARTHFORWARD.js");
const WALLTECHJUMP = require("./WALLTECHJUMP.js");
const CLIFFATTACKQUICK = require("./CLIFFATTACKQUICK.js");
const DEADUP = require("./DEADUP.js");
const FALCONDASH = require("./FALCONDASH.js");
const JAB2 = require("./JAB2.js");
const OTTOTTO = require("./OTTOTTO.js");
const SQUATRV = require("./SQUATRV.js");
const THROWNMARTHUP = require("./THROWNMARTHUP.js");
const CLIFFATTACKSLOW = require("./CLIFFATTACKSLOW.js");
const DOWNATTACK = require("./DOWNATTACK.js");
const FALCONKNEE = require("./FALCONKNEE.js");
const JAB3 = require("./JAB3.js");
const OTTOTTOWAIT = require("./OTTOTTOWAIT.js");
const SQUATWAIT = require("./SQUATWAIT.js");
const THROWNPUFFBACK = require("./THROWNPUFFBACK.js");
const CLIFFCATCH = require("./CLIFFCATCH.js");
const DOWNBOUND = require("./DOWNBOUND.js");
const FALL = require("./FALL.js");
const JUMPAERIALB = require("./JUMPAERIALB.js");
const PASS = require("./PASS.js");
const STOPCEIL = require("./STOPCEIL.js");
const THROWNPUFFDOWN = require("./THROWNPUFFDOWN.js");
const CLIFFESCAPEQUICK = require("./CLIFFESCAPEQUICK.js");
const DOWNDAMAGE = require("./DOWNDAMAGE.js");
const FALLAERIAL = require("./FALLAERIAL.js");
const JUMPAERIALF = require("./JUMPAERIALF.js");
const REBIRTH = require("./REBIRTH.js");
const TECHB = require("./TECHB.js");
const THROWNPUFFFORWARD = require("./THROWNPUFFFORWARD.js");
const THROWNFALCOBACK = require("./THROWNFALCOBACK.js");
const THROWNFALCODOWN = require("./THROWNFALCODOWN.js");
const THROWNFALCOFORWARD = require("./THROWNFALCOFORWARD.js");
const THROWNFALCOUP = require("./THROWNFALCOUP.js");
const THROWNFALCONBACK = require("./THROWNFALCONBACK");
const THROWNFALCONDOWN = require("./THROWNFALCONDOWN");
const THROWNFALCONFORWARD = require("./THROWNFALCONFORWARD");
const THROWNFALCONUP = require("./THROWNFALCONUP");
const APPEAL = require("./APPEAL.js");
const THROWNFALCONDIVE = require("./THROWNFALCONDIVE");

const fox = new LargeMap();
fox.set("ATTACKAIRB", ATTACKAIRB)
fox.set("CLIFFESCAPESLOW", CLIFFESCAPESLOW)
fox.set("DOWNSMASH", DOWNSMASH)
fox.set("FALLSPECIAL", FALLSPECIAL)
fox.set("JUMPB", JUMPB)
fox.set("REBIRTHWAIT", REBIRTHWAIT)
fox.set("TECHF", TECHF)
fox.set("THROWNPUFFUP", THROWNPUFFUP)
fox.set("ATTACKAIRD", ATTACKAIRD)
fox.set("CLIFFGETUPQUICK", CLIFFGETUPQUICK)
fox.set("DOWNSPECIALAIR", DOWNSPECIALAIR)
fox.set("FIREFOXBOUNCE", FIREFOXBOUNCE)
fox.set("JUMPF", JUMPF)
fox.set("REBOUND", REBOUND)
fox.set("TECHN", TECHN)
fox.set("THROWUP", THROWUP)
fox.set("ATTACKAIRF", ATTACKAIRF)
fox.set("CLIFFGETUPSLOW", CLIFFGETUPSLOW)
fox.set("DOWNSPECIALGROUND", DOWNSPECIALGROUND)
fox.set("FORWARDSMASH", FORWARDSMASH)
fox.set("KNEEBEND", KNEEBEND)
fox.set("RUN", RUN)
fox.set("TECHU", TECHU)
fox.set("TILTTURN", TILTTURN)
fox.set("ATTACKAIRN", ATTACKAIRN)
fox.set("CLIFFJUMPQUICK", CLIFFJUMPQUICK)
fox.set("DOWNSTANDB", DOWNSTANDB)
fox.set("FORWARDTILT", FORWARDTILT)
fox.set("LANDING", LANDING)
fox.set("RUNBRAKE", RUNBRAKE)
fox.set("THROWBACK", THROWBACK)
fox.set("UPSMASH", UPSMASH)
fox.set("ATTACKAIRU", ATTACKAIRU)
fox.set("CLIFFJUMPSLOW", CLIFFJUMPSLOW)
fox.set("DOWNSTANDF", DOWNSTANDF)
fox.set("FURAFURA", FURAFURA)
fox.set("LANDINGATTACKAIRB", LANDINGATTACKAIRB)
fox.set("RUNTURN", RUNTURN)
fox.set("THROWDOWN", THROWDOWN)
fox.set("UPSPECIALCHARGE", UPSPECIALCHARGE)
fox.set("ATTACKDASH", ATTACKDASH)
fox.set("CLIFFWAIT", CLIFFWAIT)
fox.set("DOWNSTANDN", DOWNSTANDN)
fox.set("FURASLEEPEND", FURASLEEPEND)
fox.set("LANDINGATTACKAIRD", LANDINGATTACKAIRD)
fox.set("SHIELDBREAKDOWNBOUND", SHIELDBREAKDOWNBOUND)
fox.set("THROWFORWARD", THROWFORWARD)
fox.set("UPSPECIALLAUNCH", UPSPECIALLAUNCH)
fox.set("CAPTURECUT", CAPTURECUT)
fox.set("DAMAGEFALL", DAMAGEFALL)
fox.set("DOWNTILT", DOWNTILT)
fox.set("FURASLEEPLOOP", FURASLEEPLOOP)
fox.set("LANDINGATTACKAIRF", LANDINGATTACKAIRF)
fox.set("SHIELDBREAKFALL", SHIELDBREAKFALL)
fox.set("THROWNFOXBACK", THROWNFOXBACK)
fox.set("UPTILT", UPTILT)
fox.set("CAPTUREDAMAGE", CAPTUREDAMAGE)
fox.set("DAMAGEFLYN", DAMAGEFLYN)
fox.set("DOWNWAIT", DOWNWAIT)
fox.set("FURASLEEPSTART", FURASLEEPSTART)
fox.set("LANDINGATTACKAIRN", LANDINGATTACKAIRN)
fox.set("SHIELDBREAKSTAND", SHIELDBREAKSTAND)
fox.set("THROWNFOXDOWN", THROWNFOXDOWN)
fox.set("WAIT", WAIT)
fox.set("CAPTUREPULLED", CAPTUREPULLED)
fox.set("DAMAGEN2", DAMAGEN2)
fox.set("ENTRANCE", ENTRANCE)
fox.set("GRAB", GRAB)
fox.set("LANDINGATTACKAIRU", LANDINGATTACKAIRU)
fox.set("SIDESPECIALAIR", SIDESPECIALAIR)
fox.set("THROWNFOXFORWARD", THROWNFOXFORWARD)
fox.set("WALK", WALK)
fox.set("CAPTUREWAIT", CAPTUREWAIT)
fox.set("DASH", DASH)
fox.set("ESCAPEAIR", ESCAPEAIR)
fox.set("GUARD", GUARD)
fox.set("LANDINGFALLSPECIAL", LANDINGFALLSPECIAL)
fox.set("SIDESPECIALGROUND", SIDESPECIALGROUND)
fox.set("THROWNFOXUP", THROWNFOXUP)
fox.set("WALLDAMAGE", WALLDAMAGE)
fox.set("CATCHATTACK", CATCHATTACK)
fox.set("DEADDOWN", DEADDOWN)
fox.set("ESCAPEB", ESCAPEB)
fox.set("GUARDOFF", GUARDOFF)
fox.set("MISSFOOT", MISSFOOT)
fox.set("SLEEP", SLEEP)
fox.set("THROWNMARTHBACK", THROWNMARTHBACK)
fox.set("WALLJUMP", WALLJUMP)
fox.set("CATCHCUT", CATCHCUT)
fox.set("DEADLEFT", DEADLEFT)
fox.set("ESCAPEF", ESCAPEF)
fox.set("GUARDON", GUARDON)
fox.set("NEUTRALSPECIALAIR", NEUTRALSPECIALAIR)
fox.set("SMASHTURN", SMASHTURN)
fox.set("THROWNMARTHDOWN", THROWNMARTHDOWN)
fox.set("WALLTECH", WALLTECH)
fox.set("CATCHWAIT", CATCHWAIT)
fox.set("DEADRIGHT", DEADRIGHT)
fox.set("ESCAPEN", ESCAPEN)
fox.set("JAB1", JAB1)
fox.set("NEUTRALSPECIALGROUND", NEUTRALSPECIALGROUND)
fox.set("SQUAT", SQUAT)
fox.set("THROWNMARTHFORWARD", THROWNMARTHFORWARD)
fox.set("WALLTECHJUMP", WALLTECHJUMP)
fox.set("CLIFFATTACKQUICK", CLIFFATTACKQUICK)
fox.set("DEADUP", DEADUP)
fox.set("FALCONDASH", FALCONDASH)
fox.set("JAB2", JAB2)
fox.set("OTTOTTO", OTTOTTO)
fox.set("SQUATRV", SQUATRV)
fox.set("THROWNMARTHUP", THROWNMARTHUP)
fox.set("CLIFFATTACKSLOW", CLIFFATTACKSLOW)
fox.set("DOWNATTACK", DOWNATTACK)
fox.set("FALCONKNEE", FALCONKNEE)
fox.set("JAB3", JAB3)
fox.set("OTTOTTOWAIT", OTTOTTOWAIT)
fox.set("SQUATWAIT", SQUATWAIT)
fox.set("THROWNPUFFBACK", THROWNPUFFBACK)
fox.set("CLIFFCATCH", CLIFFCATCH)
fox.set("DOWNBOUND", DOWNBOUND)
fox.set("FALL", FALL)
fox.set("JUMPAERIALB", JUMPAERIALB)
fox.set("PASS", PASS)
fox.set("STOPCEIL", STOPCEIL)
fox.set("THROWNPUFFDOWN", THROWNPUFFDOWN)
fox.set("CLIFFESCAPEQUICK", CLIFFESCAPEQUICK)
fox.set("DOWNDAMAGE", DOWNDAMAGE)
fox.set("FALLAERIAL", FALLAERIAL)
fox.set("JUMPAERIALF", JUMPAERIALF)
fox.set("REBIRTH", REBIRTH)
fox.set("TECHB", TECHB)
fox.set("THROWNPUFFFORWARD", THROWNPUFFFORWARD)
fox.set("THROWNFALCOBACK", THROWNFALCOBACK)
fox.set("THROWNFALCODOWN", THROWNFALCODOWN)
fox.set("THROWNFALCOFORWARD", THROWNFALCOFORWARD)
fox.set("THROWNFALCOUP", THROWNFALCOUP)
fox.set("THROWNFALCONBACK", THROWNFALCONBACK)
fox.set("THROWNFALCONDOWN", THROWNFALCONDOWN)
fox.set("THROWNFALCONFORWARD", THROWNFALCONFORWARD)
fox.set("THROWNFALCONUP", THROWNFALCONUP)
fox.set("APPEAL", APPEAL)
fox.set("THROWNFALCONDIVE", THROWNFALCONDIVE)

module.exports = fox;