const ATTACKAIRB = require("./ATTACKAIRB.js");
const CLIFFESCAPESLOW = require("./CLIFFESCAPESLOW.js");
const DOWNSMASH = require("./DOWNSMASH.js");
const FALLSPECIAL = require("./FALLSPECIAL.js");
const JUMPB = require("./JUMPB.js");
const REBIRTHWAIT = require("./REBIRTHWAIT.js");
const TECHF = require("./TECHF.js");
const THROWNPUFFUP = require("./THROWNPUFFUP.js");
const ATTACKAIRD = require("./ATTACKAIRD.js");
const CLIFFGETUPQUICK = require("./CLIFFGETUPQUICK.js");
const DOWNSPECIALAIR = require("./DOWNSPECIALAIR.js");
const FIREFOXBOUNCE = require("./FIREFOXBOUNCE.js");
const JUMPF = require("./JUMPF.js");
const REBOUND = require("./REBOUND.js");
const TECHN = require("./TECHN.js");
const THROWUP = require("./THROWUP.js");
const ATTACKAIRF = require("./ATTACKAIRF.js");
const CLIFFGETUPSLOW = require("./CLIFFGETUPSLOW.js");
const DOWNSPECIALGROUND = require("./DOWNSPECIALGROUND.js");
const FORWARDSMASH = require("./FORWARDSMASH.js");
const KNEEBEND = require("./KNEEBEND.js");
const RUN = require("./RUN.js");
const TECHU = require("./TECHU.js");
const TILTTURN = require("./TILTTURN.js");
const ATTACKAIRN = require("./ATTACKAIRN.js");
const CLIFFJUMPQUICK = require("./CLIFFJUMPQUICK.js");
const DOWNSTANDB = require("./DOWNSTANDB.js");
const FORWARDTILT = require("./FORWARDTILT.js");
const LANDING = require("./LANDING.js");
const RUNBRAKE = require("./RUNBRAKE.js");
const THROWBACK = require("./THROWBACK.js");
const UPSMASH = require("./UPSMASH.js");
const ATTACKAIRU = require("./ATTACKAIRU.js");
const CLIFFJUMPSLOW = require("./CLIFFJUMPSLOW.js");
const DOWNSTANDF = require("./DOWNSTANDF.js");
const FURAFURA = require("./FURAFURA.js");
const LANDINGATTACKAIRB = require("./LANDINGATTACKAIRB.js");
const RUNTURN = require("./RUNTURN.js");
const THROWDOWN = require("./THROWDOWN.js");
const UPSPECIALCHARGE = require("./UPSPECIALCHARGE.js");
const ATTACKDASH = require("./ATTACKDASH.js");
const CLIFFWAIT = require("./CLIFFWAIT.js");
const DOWNSTANDN = require("./DOWNSTANDN.js");
const FURASLEEPEND = require("./FURASLEEPEND.js");
const LANDINGATTACKAIRD = require("./LANDINGATTACKAIRD.js");
const SHIELDBREAKDOWNBOUND = require("./SHIELDBREAKDOWNBOUND.js");
const THROWFORWARD = require("./THROWFORWARD.js");
const UPSPECIALLAUNCH = require("./UPSPECIALLAUNCH.js");
const CAPTURECUT = require("./CAPTURECUT.js");
const DAMAGEFALL = require("./DAMAGEFALL.js");
const DOWNTILT = require("./DOWNTILT.js");
const FURASLEEPLOOP = require("./FURASLEEPLOOP.js");
const LANDINGATTACKAIRF = require("./LANDINGATTACKAIRF.js");
const SHIELDBREAKFALL = require("./SHIELDBREAKFALL.js");
const THROWNFOXBACK = require("./THROWNFOXBACK.js");
const UPTILT = require("./UPTILT.js");
const CAPTUREDAMAGE = require("./CAPTUREDAMAGE.js");
const DAMAGEFLYN = require("./DAMAGEFLYN.js");
const DOWNWAIT = require("./DOWNWAIT.js");
const FURASLEEPSTART = require("./FURASLEEPSTART.js");
const LANDINGATTACKAIRN = require("./LANDINGATTACKAIRN.js");
const SHIELDBREAKSTAND = require("./SHIELDBREAKSTAND.js");
const THROWNFOXDOWN = require("./THROWNFOXDOWN.js");
const WAIT = require("./WAIT.js");
const CAPTUREPULLED = require("./CAPTUREPULLED.js");
const DAMAGEN2 = require("./DAMAGEN2.js");
const ENTRANCE = require("./ENTRANCE.js");
const GRAB = require("./GRAB.js");
const LANDINGATTACKAIRU = require("./LANDINGATTACKAIRU.js");
const SIDESPECIALAIR = require("./SIDESPECIALAIR.js");
const THROWNFOXFORWARD = require("./THROWNFOXFORWARD.js");
const WALK = require("./WALK.js");
const CAPTUREWAIT = require("./CAPTUREWAIT.js");
const DASH = require("./DASH.js");
const ESCAPEAIR = require("./ESCAPEAIR.js");
const GUARD = require("./GUARD.js");
const LANDINGFALLSPECIAL = require("./LANDINGFALLSPECIAL.js");
const SIDESPECIALGROUND = require("./SIDESPECIALGROUND.js");
const THROWNFOXUP = require("./THROWNFOXUP.js");
const WALLDAMAGE = require("./WALLDAMAGE.js");
const CATCHATTACK = require("./CATCHATTACK.js");
const DEADDOWN = require("./DEADDOWN.js");
const ESCAPEB = require("./ESCAPEB.js");
const GUARDOFF = require("./GUARDOFF.js");
const MISSFOOT = require("./MISSFOOT.js");
const SLEEP = require("./SLEEP.js");
const THROWNMARTHBACK = require("./THROWNMARTHBACK.js");
const WALLJUMP = require("./WALLJUMP.js");
const CATCHCUT = require("./CATCHCUT.js");
const DEADLEFT = require("./DEADLEFT.js");
const ESCAPEF = require("./ESCAPEF.js");
const GUARDON = require("./GUARDON.js");
const NEUTRALSPECIALAIR = require("./NEUTRALSPECIALAIR.js");
const SMASHTURN = require("./SMASHTURN.js");
const THROWNMARTHDOWN = require("./THROWNMARTHDOWN.js");
const WALLTECH = require("./WALLTECH.js");
const CATCHWAIT = require("./CATCHWAIT.js");
const DEADRIGHT = require("./DEADRIGHT.js");
const ESCAPEN = require("./ESCAPEN.js");
const JAB1 = require("./JAB1.js");
const NEUTRALSPECIALGROUND = require("./NEUTRALSPECIALGROUND.js");
const SQUAT = require("./SQUAT.js");
const THROWNMARTHFORWARD = require("./THROWNMARTHFORWARD.js");
const WALLTECHJUMP = require("./WALLTECHJUMP.js");
const CLIFFATTACKQUICK = require("./CLIFFATTACKQUICK.js");
const DEADUP = require("./DEADUP.js");
const FALCONDASH = require("./FALCONDASH.js");
const JAB2 = require("./JAB2.js");
const OTTOTTO = require("./OTTOTTO.js");
const SQUATRV = require("./SQUATRV.js");
const THROWNMARTHUP = require("./THROWNMARTHUP.js");
const CLIFFATTACKSLOW = require("./CLIFFATTACKSLOW.js");
const DOWNATTACK = require("./DOWNATTACK.js");
const FALCONKNEE = require("./FALCONKNEE.js");
const JAB3 = require("./JAB3.js");
const OTTOTTOWAIT = require("./OTTOTTOWAIT.js");
const SQUATWAIT = require("./SQUATWAIT.js");
const THROWNPUFFBACK = require("./THROWNPUFFBACK.js");
const CLIFFCATCH = require("./CLIFFCATCH.js");
const DOWNBOUND = require("./DOWNBOUND.js");
const FALL = require("./FALL.js");
const JUMPAERIALB = require("./JUMPAERIALB.js");
const PASS = require("./PASS.js");
const STOPCEIL = require("./STOPCEIL.js");
const THROWNPUFFDOWN = require("./THROWNPUFFDOWN.js");
const CLIFFESCAPEQUICK = require("./CLIFFESCAPEQUICK.js");
const DOWNDAMAGE = require("./DOWNDAMAGE.js");
const FALLAERIAL = require("./FALLAERIAL.js");
const JUMPAERIALF = require("./JUMPAERIALF.js");
const REBIRTH = require("./REBIRTH.js");
const TECHB = require("./TECHB.js");
const THROWNPUFFFORWARD = require("./THROWNPUFFFORWARD.js");
const THROWNFALCOBACK = require("./THROWNFALCOBACK.js");
const THROWNFALCODOWN = require("./THROWNFALCODOWN.js");
const THROWNFALCOFORWARD = require("./THROWNFALCOFORWARD.js");
const THROWNFALCOUP = require("./THROWNFALCOUP.js");
const THROWNFALCONBACK = require("./THROWNFALCONBACK");
const THROWNFALCONDOWN = require("./THROWNFALCONDOWN");
const THROWNFALCONFORWARD = require("./THROWNFALCONFORWARD");
const THROWNFALCONUP = require("./THROWNFALCONUP");
const APPEAL = require("./APPEAL.js");
const THROWNFALCONDIVE = require("./THROWNFALCONDIVE");

module.exports = {
  ATTACKAIRB: ATTACKAIRB,
  CLIFFESCAPESLOW: CLIFFESCAPESLOW,
  DOWNSMASH: DOWNSMASH,
  FALLSPECIAL: FALLSPECIAL,
  JUMPB: JUMPB,
  REBIRTHWAIT: REBIRTHWAIT,
  TECHF: TECHF,
  THROWNPUFFUP: THROWNPUFFUP,
  ATTACKAIRD: ATTACKAIRD,
  CLIFFGETUPQUICK: CLIFFGETUPQUICK,
  DOWNSPECIALAIR: DOWNSPECIALAIR,
  FIREFOXBOUNCE: FIREFOXBOUNCE,
  JUMPF: JUMPF,
  REBOUND: REBOUND,
  TECHN: TECHN,
  THROWUP: THROWUP,
  ATTACKAIRF: ATTACKAIRF,
  CLIFFGETUPSLOW: CLIFFGETUPSLOW,
  DOWNSPECIALGROUND: DOWNSPECIALGROUND,
  FORWARDSMASH: FORWARDSMASH,
  KNEEBEND: KNEEBEND,
  RUN: RUN,
  TECHU: TECHU,
  TILTTURN: TILTTURN,
  ATTACKAIRN: ATTACKAIRN,
  CLIFFJUMPQUICK: CLIFFJUMPQUICK,
  DOWNSTANDB: DOWNSTANDB,
  FORWARDTILT: FORWARDTILT,
  LANDING: LANDING,
  RUNBRAKE: RUNBRAKE,
  THROWBACK: THROWBACK,
  UPSMASH: UPSMASH,
  ATTACKAIRU: ATTACKAIRU,
  CLIFFJUMPSLOW: CLIFFJUMPSLOW,
  DOWNSTANDF: DOWNSTANDF,
  FURAFURA: FURAFURA,
  LANDINGATTACKAIRB: LANDINGATTACKAIRB,
  RUNTURN: RUNTURN,
  THROWDOWN: THROWDOWN,
  UPSPECIALCHARGE: UPSPECIALCHARGE,
  ATTACKDASH: ATTACKDASH,
  CLIFFWAIT: CLIFFWAIT,
  DOWNSTANDN: DOWNSTANDN,
  FURASLEEPEND: FURASLEEPEND,
  LANDINGATTACKAIRD: LANDINGATTACKAIRD,
  SHIELDBREAKDOWNBOUND: SHIELDBREAKDOWNBOUND,
  THROWFORWARD: THROWFORWARD,
  UPSPECIALLAUNCH: UPSPECIALLAUNCH,
  CAPTURECUT: CAPTURECUT,
  DAMAGEFALL: DAMAGEFALL,
  DOWNTILT: DOWNTILT,
  FURASLEEPLOOP: FURASLEEPLOOP,
  LANDINGATTACKAIRF: LANDINGATTACKAIRF,
  SHIELDBREAKFALL: SHIELDBREAKFALL,
  THROWNFOXBACK: THROWNFOXBACK,
  UPTILT: UPTILT,
  CAPTUREDAMAGE: CAPTUREDAMAGE,
  DAMAGEFLYN: DAMAGEFLYN,
  DOWNWAIT: DOWNWAIT,
  FURASLEEPSTART: FURASLEEPSTART,
  LANDINGATTACKAIRN: LANDINGATTACKAIRN,
  SHIELDBREAKSTAND: SHIELDBREAKSTAND,
  THROWNFOXDOWN: THROWNFOXDOWN,
  WAIT: WAIT,
  CAPTUREPULLED: CAPTUREPULLED,
  DAMAGEN2: DAMAGEN2,
  ENTRANCE: ENTRANCE,
  GRAB: GRAB,
  LANDINGATTACKAIRU: LANDINGATTACKAIRU,
  SIDESPECIALAIR: SIDESPECIALAIR,
  THROWNFOXFORWARD: THROWNFOXFORWARD,
  WALK: WALK,
  CAPTUREWAIT: CAPTUREWAIT,
  DASH: DASH,
  ESCAPEAIR: ESCAPEAIR,
  GUARD: GUARD,
  LANDINGFALLSPECIAL: LANDINGFALLSPECIAL,
  SIDESPECIALGROUND: SIDESPECIALGROUND,
  THROWNFOXUP: THROWNFOXUP,
  WALLDAMAGE: WALLDAMAGE,
  CATCHATTACK: CATCHATTACK,
  DEADDOWN: DEADDOWN,
  ESCAPEB: ESCAPEB,
  GUARDOFF: GUARDOFF,
  MISSFOOT: MISSFOOT,
  SLEEP: SLEEP,
  THROWNMARTHBACK: THROWNMARTHBACK,
  WALLJUMP: WALLJUMP,
  CATCHCUT: CATCHCUT,
  DEADLEFT: DEADLEFT,
  ESCAPEF: ESCAPEF,
  GUARDON: GUARDON,
  NEUTRALSPECIALAIR: NEUTRALSPECIALAIR,
  SMASHTURN: SMASHTURN,
  THROWNMARTHDOWN: THROWNMARTHDOWN,
  WALLTECH: WALLTECH,
  CATCHWAIT: CATCHWAIT,
  DEADRIGHT: DEADRIGHT,
  ESCAPEN: ESCAPEN,
  JAB1: JAB1,
  NEUTRALSPECIALGROUND: NEUTRALSPECIALGROUND,
  SQUAT: SQUAT,
  THROWNMARTHFORWARD: THROWNMARTHFORWARD,
  WALLTECHJUMP: WALLTECHJUMP,
  CLIFFATTACKQUICK: CLIFFATTACKQUICK,
  DEADUP: DEADUP,
  FALCONDASH: FALCONDASH,
  JAB2: JAB2,
  OTTOTTO: OTTOTTO,
  SQUATRV: SQUATRV,
  THROWNMARTHUP: THROWNMARTHUP,
  CLIFFATTACKSLOW: CLIFFATTACKSLOW,
  DOWNATTACK: DOWNATTACK,
  FALCONKNEE: FALCONKNEE,
  JAB3: JAB3,
  OTTOTTOWAIT: OTTOTTOWAIT,
  SQUATWAIT: SQUATWAIT,
  THROWNPUFFBACK: THROWNPUFFBACK,
  CLIFFCATCH: CLIFFCATCH,
  DOWNBOUND: DOWNBOUND,
  FALL: FALL,
  JUMPAERIALB: JUMPAERIALB,
  PASS: PASS,
  STOPCEIL: STOPCEIL,
  THROWNPUFFDOWN: THROWNPUFFDOWN,
  CLIFFESCAPEQUICK: CLIFFESCAPEQUICK,
  DOWNDAMAGE: DOWNDAMAGE,
  FALLAERIAL: FALLAERIAL,
  JUMPAERIALF: JUMPAERIALF,
  REBIRTH: REBIRTH,
  TECHB: TECHB,
  THROWNPUFFFORWARD: THROWNPUFFFORWARD,
  THROWNFALCOBACK: THROWNFALCOBACK,
  THROWNFALCODOWN: THROWNFALCODOWN,
  THROWNFALCOFORWARD: THROWNFALCOFORWARD,
  THROWNFALCOUP: THROWNFALCOUP,
  THROWNFALCONBACK: THROWNFALCONBACK,
  THROWNFALCONDOWN: THROWNFALCONDOWN,
  THROWNFALCONFORWARD: THROWNFALCONFORWARD,
  THROWNFALCONUP: THROWNFALCONUP,
  APPEAL: APPEAL,
  THROWNFALCONDIVE: THROWNFALCONDIVE
};
